{
    "bugid": "1389414",
    "cveid": [
        "CVE-2016-9013"
    ],
    "summary": "CVE-2016-9013 python-django: user with hardcoded password created when running tests on Oracle",
    "alias": "CVE-2016-9013",
    "product": "Security Response",
    "hardware": "All",
    "os": "Linux",
    "url": "",
    "reported_date": "2016-10-27 14:26 UTC byMartin Prpi\u010d",
    "attachment": [
        "https://bugzilla-attachments.redhat.com/attachment.cgi?id=1214631",
        "https://bugzilla-attachments.redhat.com/attachment.cgi?id=1214632",
        "https://bugzilla-attachments.redhat.com/attachment.cgi?id=1214633",
        "https://bugzilla-attachments.redhat.com/attachment.cgi?id=1214634"
    ],
    "comment": [
        "The following flaw was reported in Django:\n\nWhen running tests with an Oracle database, Django creates a temporary database user. In older versions, if a password isn't manually specified in the database settings 'TEST' dictionary, a hardcoded password is used. This could allow an attacker with network access to the database server to connect.\n\nThis user is usually dropped after the test suite completes, but not when using the 'manage.py test --keepdb' option or if the user has an active session (such as an attacker's connection).\n\nA randomly generated password is now used for each test run.",
        "Acknowledgments:\n\nName: the Django project",
        "Createdattachment 1214631[details]oracle-1.10.x.diff",
        "Createdattachment 1214632[details]oracle-1.8.x.diff",
        "Createdattachment 1214633[details]oracle-1.9.x.diff",
        "Createdattachment 1214634[details]oracle-master.diff",
        "Public via:https://www.djangoproject.com/weblog/2016/nov/01/security-releases/",
        "Created Django14 tracking bugs for this issue:\n\nAffects: epel-6 [bug 1390685]",
        "Created python-django tracking bugs for this issue:\n\nAffects: fedora-all [bug 1390684]",
        "Created python-django tracking bugs for this issue:\n\nAffects: epel-7 [bug 1390687]"
    ]
}